version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity   # Overrides default command so things don't shut down after the process ends.
    network_mode: service:db  # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.

  db:
    image: memgraph/memgraph-platform:latest
    restart: unless-stopped
    volumes:
      - mg_lib:/var/lib/memgraph  # directory containing data, enables data persistency
      - mg_log:/var/log/memgraph  # directory containing log files
      - mg_etc:/etc/memgraph      # directory containing the configuration file

volumes:
  mg_lib:
  mg_log:
  mg_etc:
